services:
  backend-url-shortener:
    command: npm run dev
    build: .
    image: node-backend-url-shortener
    container_name: backend-url-shortener
    ports:
      - "3000:3000"
    environment:
      PORT: ${PORT}
      MONGO_URL: ${MONGO_URL}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    volumes:
      - .:/app

  mongo-db:
    image: mongo:8.2.4
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017